server:
  port: 8080
  servlet:
    context-path: /bootcamp

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: postgres://dgijpdrrosezzr:6f84b005b1e4006821fdff259718364138ba566c72d1261fd91ec3e3367f5b22@ec2-54-225-228-142.compute-1.amazonaws.com:5432/d6oin0hkcu6gjq
    username: dgijpdrrosezzr
    password: 6f84b005b1e4006821fdff259718364138ba566c72d1261fd91ec3e3367f5b22
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: none

application:
  description: Projeto criado para o bootcamp DIO - Santander